### ISSUE TITLE
InterruptedException waiting for shSync

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/qDup#110]
Hi,
 I am seeing this error thrown by qDup

```
10:37:58.166 [qdup-scheduled-11] ERROR io.hyperfoil.tools.qdup.SshSession - Interrupted waiting for shSync (exit $__qdup_ec);

java.lang.InterruptedException: null

	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1040)

	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)

	at java.base/java.util.concurrent.Semaphore.acquire(Semaphore.java:318)

	at io.hyperfoil.tools.qdup.SshSession.shSync(SshSession.java:785)

	at io.hyperfoil.tools.qdup.SshSession.shSync(SshSession.java:775)

	at io.hyperfoil.tools.qdup.cmd.impl.Sh.postRun(Sh.java:110)

	at io.hyperfoil.tools.qdup.cmd.ScriptContext.next(ScriptContext.java:307)

	at io.hyperfoil.tools.qdup.cmd.impl.Sh.lambda$run$0(Sh.java:71)

	at io.hyperfoil.tools.qdup.SshSession.callback(SshSession.java:800)

	at io.hyperfoil.tools.qdup.SshSession.lambda$shObservers$2(SshSession.java:351)

	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)

	at io.hyperfoil.tools.qdup.SshSession.shObservers(SshSession.java:350)

	at io.hyperfoil.tools.qdup.SshSession.lambda$connect$9(SshSession.java:576)

	at io.hyperfoil.tools.qdup.stream.SuffixStream.lambda$callConsumers$0(SuffixStream.java:240)

	at java.base/java.lang.Iterable.forEach(Iterable.java:75)

	at io.hyperfoil.tools.qdup.stream.SuffixStream.callConsumers(SuffixStream.java:240)

	at io.hyperfoil.tools.qdup.stream.SuffixStream$FoundRunnable.run(SuffixStream.java:42)

	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

	at java.base/java.lang.Thread.run(Thread.java:834)

script returned exit code 1
```

 This is for a script that is executing one of the setup phase step.

**Comment by whitingjr** [comment]
bah, in this situation there was an error in an earlier step. This exception is to be expected when qDup is terminating.
