### ISSUE TITLE
NPE during cleanup scripts.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/qDup#204]
A NullPointerException was thrown during the cleanup phase.

```
14:10:56.539 qdup_controller_role-cleanup:5370@mwperf-server01:read-state: false
14:10:56.539 qdup_controller_role-cleanup:5370@mwperf-server01:read-state: false
14:10:56.539 qdup_controller_role-cleanup:5370@mwperf-server01:script-cmd: cleanup
14:10:56.539 qdup_controller_role-cleanup:5370@mwperf-server01:cleanup
14:10:56.540 qdup_controller_role-cleanup:5370@mwperf-server01:read-state: ${{FORCE}}
14:10:56.540 qdup_controller_role-cleanup:5370@mwperf-server01:read-state: false
14:10:56.540 qdup_controller_role-cleanup:5370@mwperf-server01:read-state: false
14:10:56.540 qdup_controller_role-cleanup:5370@mwperf-server01:script-cmd: kill-grep
14:10:56.540 qdup_controller_role-cleanup:5370@mwperf-server01:kill-grep
14:10:56.847 qdup_controller_role-cleanup:5370@mwperf-server01:ps -ef | grep simulator | grep -v grep | awk '{print $2}' | xargs -r kill -9
14:10:56.852 [qdup-command-2] INFO  io.hyperfoil.tools.qdup.Run - run-1688738489809 runPendingDownloads
14:10:56.857 [qdup-command-2] ERROR io.hyperfoil.tools.qdup.QDup - UNCAUGHT:qdup-command-2 null
java.lang.NullPointerException: null
	at io.hyperfoil.tools.qdup.State.lambda$filter$5(State.java:434)
	at io.hyperfoil.tools.yaup.json.Json.lambda$forEach$26(Json.java:1535)
	at java.base/java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:671)
	at io.hyperfoil.tools.yaup.json.Json.forEach(Json.java:1535)
	at io.hyperfoil.tools.qdup.State.filter(State.java:430)
	at io.hyperfoil.tools.qdup.State.tree(State.java:420)
	at io.hyperfoil.tools.qdup.State.tree(State.java:426)
	at io.hyperfoil.tools.qdup.State.tree(State.java:398)
	at io.hyperfoil.tools.qdup.Run.postRun(Run.java:850)
	at io.hyperfoil.tools.qdup.Run.nextStage(Run.java:246)
	at io.hyperfoil.tools.qdup.Run.postStop(Run.java:183)
	at io.hyperfoil.tools.qdup.cmd.Dispatcher.lambda$checkActiveCount$14(Dispatcher.java:456)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.hyperfoil.tools.qdup.cmd.Dispatcher.lambda$checkActiveCount$15(Dispatcher.java:456)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

qDup v 0.7.1
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment Temurin-11.0.19+7 (build 11.0.19+7)
OpenJDK 64-Bit Server VM Temurin-11.0.19+7 (build 11.0.19+7, mixed mode)
$ uname -a
Linux f37lite 6.2.15-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu May 11 15:56:33 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by willr3** [comment]
I think this was fixed in de1ecb4303e08841e64645565335f6998d170c3c. Please open again if it is still occurring.
