### ISSUE TITLE
[Mac-os]: Qdup latest version fails to execute and old version throws intermittent errors

### ISSUE THREAD

**Issue by ShivangGoswami** [Hyperfoil/qDup#205]
Java Environment:

```console
shivanggoswami@MacBook-Pro resource-sizing-qdup-scripts % java --version
openjdk 22-ea 2024-03-19
OpenJDK Runtime Environment (build 22-ea+19-1460)
OpenJDK 64-Bit Server VM (build 22-ea+19-1460, mixed mode, sharing
```

Qdup Version(cloned from [maven repos)](https://repo1.maven.org/maven2/io/hyperfoil/tools/qDup/):

- qdup.jar: version 0.6.13
- qdup-6.jar: version 0.6.21
- qdup-7.jar: version 0.7.4

Qdup Script: 

```yaml
scripts:
    tryme:
    - sh: whoami
    - sh: date
    - sh: echo ${{message}}
hosts:
    server: root@localhost:1234
roles:
    test:
        hosts:
        - server
        run-scripts:
        - tryme
states:
    message: Hello, qDup!
```

Ssh server is a podman container:
```
shivanggoswami@MacBook-Pro ~ % podman ps -a
CONTAINER ID  IMAGE                       COMMAND     CREATED         STATUS         PORTS                 NAMES
1bdc29330340  localhost/sshserver:latest              11 minutes ago  Up 11 minutes  0.0.0.0:1234->22/tcp  ssh-server01
```

Scenarios:

- Error with latest version
   ```console
   shivanggoswami@Shivangs-MacBook-Pro resource-sizing-qdup-scripts % java -jar qDup-7.jar -C -B ./tmp -I ~/.ssh/id_podman_vm sample.yaml
   Exception in thread "main" java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.ensureClassInitialized(java.lang.Class)'
        at com.oracle.truffle.api.library.LibraryFactory.ensureLibraryInitialized(LibraryFactory.java:384)
        at com.oracle.truffle.api.library.LibraryFactory.getUncached(LibraryFactory.java:364)
        at com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:210)
        at com.oracle.truffle.api.interop.InteropLibraryGen.<init>(InteropLibraryGen.java:170)
        at com.oracle.truffle.api.interop.InteropLibraryGen.<clinit>(InteropLibraryGen.java:161)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:537)
        at java.base/java.lang.Class.forName(Class.java:516)
        at com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:771)
        at com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:734)
        at com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:727)
        at com.oracle.truffle.api.interop.InteropLibrary.<clinit>(InteropLibrary.java:2875)
        at com.oracle.truffle.polyglot.PolyglotValueDispatch.<clinit>(PolyglotValueDispatch.java:156)
        at com.oracle.truffle.polyglot.PolyglotImpl.initialize(PolyglotImpl.java:143)
        at org.graalvm.polyglot.impl.AbstractPolyglotImpl.setConstructors(AbstractPolyglotImpl.java:233)
        at org.graalvm.polyglot.Engine$1.loadAndValidateProviders(Engine.java:821)
        at org.graalvm.polyglot.Engine$1.run(Engine.java:794)
        at org.graalvm.polyglot.Engine$1.run(Engine.java:768)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:768)
        at org.graalvm.polyglot.Engine.access$000(Engine.java:109)
        at org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:133)
        at org.graalvm.polyglot.Engine.getImpl(Engine.java:320)
        at org.graalvm.polyglot.Engine$Builder.build(Engine.java:559)
        at io.hyperfoil.tools.yaup.StringUtil.jsEval(StringUtil.java:150)
        at io.hyperfoil.tools.yaup.StringUtil.populatePattern(StringUtil.java:462)
        at io.hyperfoil.tools.yaup.StringUtil.populatePattern(StringUtil.java:325)
        at io.hyperfoil.tools.qdup.cmd.Cmd.populateStateVariables(Cmd.java:585)
        at io.hyperfoil.tools.qdup.Host.lambda$populateList$15(Host.java:474)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at io.hyperfoil.tools.qdup.Host.populateList(Host.java:474)
        at io.hyperfoil.tools.qdup.Host.populate(Host.java:489)
        at io.hyperfoil.tools.qdup.config.RunConfigBuilder.buildConfig(RunConfigBuilder.java:442)
        at io.hyperfoil.tools.qdup.QDup.run(QDup.java:579)
        at io.hyperfoil.tools.qdup.QDup.main(QDup.java:451)
   ``` 
- Error in version 0.6.21
  ```console
  shivanggoswami@Shivangs-MacBook-Pro resource-sizing-qdup-scripts % java -jar qDup-6.jar -C -B ./tmp -i ~/.ssh/id_podman_vm sample.yaml
  Exception in thread "main" java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.ensureClassInitialized(java.lang.Class)'
          at com.oracle.truffle.api.library.LibraryFactory.ensureLibraryInitialized(LibraryFactory.java:384)
          at com.oracle.truffle.api.library.LibraryFactory.getUncached(LibraryFactory.java:364)
          at com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:210)
          at com.oracle.truffle.api.interop.InteropLibraryGen.<init>(InteropLibraryGen.java:170)
          at com.oracle.truffle.api.interop.InteropLibraryGen.<clinit>(InteropLibraryGen.java:161)
          at java.base/java.lang.Class.forName0(Native Method)
          at java.base/java.lang.Class.forName(Class.java:537)
          at java.base/java.lang.Class.forName(Class.java:516)
          at com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:771)
          at com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:734)
          at com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:727)
          at com.oracle.truffle.api.interop.InteropLibrary.<clinit>(InteropLibrary.java:2875)
          at com.oracle.truffle.polyglot.PolyglotValueDispatch.<clinit>(PolyglotValueDispatch.java:156)
          at com.oracle.truffle.polyglot.PolyglotImpl.initialize(PolyglotImpl.java:143)
          at org.graalvm.polyglot.impl.AbstractPolyglotImpl.setConstructors(AbstractPolyglotImpl.java:233)
          at org.graalvm.polyglot.Engine$1.loadAndValidateProviders(Engine.java:821)
          at org.graalvm.polyglot.Engine$1.run(Engine.java:794)
          at org.graalvm.polyglot.Engine$1.run(Engine.java:768)
          at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
          at org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:768)
          at org.graalvm.polyglot.Engine.access$000(Engine.java:109)
          at org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:133)
          at org.graalvm.polyglot.Engine.getImpl(Engine.java:320)
          at org.graalvm.polyglot.Engine$Builder.build(Engine.java:559)
          at io.hyperfoil.tools.yaup.StringUtil.jsEval(StringUtil.java:150)
          at io.hyperfoil.tools.yaup.StringUtil.populatePattern(StringUtil.java:462)
          at io.hyperfoil.tools.yaup.StringUtil.populatePattern(StringUtil.java:325)
          at io.hyperfoil.tools.qdup.cmd.Cmd.populateStateVariables(Cmd.java:585)
          at io.hyperfoil.tools.qdup.Host.lambda$populateList$7(Host.java:441)
          at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
          at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
          at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
          at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
          at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
          at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
          at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
          at io.hyperfoil.tools.qdup.Host.populateList(Host.java:441)
          at io.hyperfoil.tools.qdup.Host.populate(Host.java:452)
          at io.hyperfoil.tools.qdup.config.RunConfigBuilder.buildConfig(RunConfigBuilder.java:442)
          at io.hyperfoil.tools.qdup.QDup.run(QDup.java:560)
          at io.hyperfoil.tools.qdup.QDup.main(QDup.java:437)
  ```
- Executes in version 0.6.13
  ```console
  shivanggoswami@Shivangs-MacBook-Pro resource-sizing-qdup-scripts % java -jar qDup.jar -C -B ./tmp -i ~/.ssh/id_podman_vm sample.yaml 
  11:53:01.312 [main] INFO  io.hyperfoil.tools.qdup.QDup - Starting with output path = ./tmp
  11:53:01.592 [main] INFO  io.hyperfoil.tools.qdup.JsonServer - listening at dhcp-9-239-10-140.c4p-in.ibmmobiledemo.com:31337
  11:53:01.719 Running qDup version 0.6.13 @ 00a1831
  11:53:01.724 run-1698733381197 starting state:
   message = Hello, qDup!
  
  11:53:01.728 [main] INFO  i.h.tools.qdup.cmd.Dispatcher - starting 0 scripts
  11:53:01.891 [qdup-command-1] INFO  o.a.s.c.u.s.e.EdDSASecurityProviderRegistrar - getOrCreateProvider(EdDSA) created instance of net.i2p.crypto.eddsa.EdDSASecurityProvider
  11:53:02.000 [qdup-command-1] INFO  o.a.s.c.i.DefaultIoServiceFactoryFactory - No detected/configured IoServiceFactoryFactory using Nio2ServiceFactoryFactory
  11:53:02.014 [qdup-command-1] INFO  o.a.s.c.c.h.DefaultConfigFileHostEntryResolver - resolveEffectiveResolver(root@localhost:1234) loaded 9 entries from /Users/shivanggoswami/.ssh/config
  11:53:02.640 [qdup-command-0] INFO  i.h.tools.qdup.cmd.Dispatcher - starting 1 scripts
  11:53:02.641 [qdup-command-0] INFO  i.h.tools.qdup.cmd.Dispatcher - starting nanny
  11:53:02.645 tryme:14@localhost:script-cmd: tryme
  11:53:02.647 tryme:14@localhost:tryme
  11:53:02.990 tryme:14@localhost:whoami
  root
  11:53:03.325 tryme:14@localhost:date
  Tue Oct 31 06:23:03 UTC 2023
  11:53:03.660 tryme:14@localhost:echo Hello, qDup!
  Hello, qDup!
  11:53:03.673 [qdup-command-8] INFO  io.hyperfoil.tools.qdup.Run - run-1698733381197 runPendingDownloads
  11:53:03.674 [qdup-command-8] INFO  io.hyperfoil.tools.qdup.Run - run-1698733381197 -> ./tmp.queueCleanupScripts
  11:53:03.674 [qdup-command-8] INFO  i.h.tools.qdup.cmd.Dispatcher - starting 0 scripts
  11:53:03.676 [qdup-command-9] INFO  io.hyperfoil.tools.qdup.Run - run-1698733381197 runPendingDownloads
  11:53:03.677 run-1698733381197 closing state:
   message = Hello, qDup!
   localhost : 
     tryme : 
       id=7 : 
  
  Finished in 01.980 at ./tmp
  11:53:04.710 [shutdown-abort] WARN  io.hyperfoil.tools.qdup.Run - Skipping cleanup - Abort has been defined to not run any cleanup scripts
  11:53:04.710 [shutdown-abort] WARN  i.h.tools.qdup.cmd.Dispatcher - ignoring stop call when already stopped
  ```
- Error in version 0.6.13 
  ```console
  shivanggoswami@Shivangs-MacBook-Pro resource-sizing-qdup-scripts % java -jar qDup.jar -C -B ./tmp -i ~/.ssh/id_podman_vm setup.yaml scripts
  Exception in thread "main" java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.ensureClassInitialized(java.lang.Class)'
          at com.oracle.truffle.api.library.LibraryFactory.ensureLibraryInitialized(LibraryFactory.java:306)
          at com.oracle.truffle.api.library.LibraryFactory.getUncached(LibraryFactory.java:287)
          at com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:177)
          at com.oracle.truffle.api.interop.InteropLibraryGen.<init>(InteropLibraryGen.java:129)
          at com.oracle.truffle.api.interop.InteropLibraryGen.<clinit>(InteropLibraryGen.java:120)
          at java.base/java.lang.Class.forName0(Native Method)
          at java.base/java.lang.Class.forName(Class.java:537)
          at java.base/java.lang.Class.forName(Class.java:516)
          at com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:636)
          at com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:599)
          at com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:592)
          at com.oracle.truffle.api.interop.InteropLibrary.<clinit>(InteropLibrary.java:1547)
          at com.oracle.truffle.polyglot.PolyglotValue.<clinit>(PolyglotValue.java:123)
          at com.oracle.truffle.polyglot.PolyglotImpl.initialize(PolyglotImpl.java:119)
          at org.graalvm.polyglot.impl.AbstractPolyglotImpl.setConstructors(AbstractPolyglotImpl.java:208)
          at org.graalvm.polyglot.Engine$1.run(Engine.java:723)
          at org.graalvm.polyglot.Engine$1.run(Engine.java:691)
          at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
          at org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:691)
          at org.graalvm.polyglot.Engine.access$000(Engine.java:105)
          at org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:114)
          at org.graalvm.polyglot.Engine.getImpl(Engine.java:287)
          at org.graalvm.polyglot.Engine$Builder.build(Engine.java:525)
          at org.graalvm.polyglot.Context$Builder.build(Context.java:1489)
          at io.hyperfoil.tools.yaup.StringUtil.jsEval(StringUtil.java:156)
          at io.hyperfoil.tools.yaup.StringUtil.populatePattern(StringUtil.java:424)
          at io.hyperfoil.tools.yaup.StringUtil.populatePattern(StringUtil.java:324)
          at io.hyperfoil.tools.yaup.StringUtil.getPatternNames(StringUtil.java:309)
          at io.hyperfoil.tools.qdup.cmd.Cmd.getStateVariables(Cmd.java:523)
          at io.hyperfoil.tools.qdup.config.rule.UndefinedStateVariables.scan(UndefinedStateVariables.java:172)
          at io.hyperfoil.tools.qdup.config.RunSummary.lambda$scan$6(RunSummary.java:65)
          at java.base/java.util.HashMap$Values.forEach(HashMap.java:1073)
          at io.hyperfoil.tools.qdup.config.RunSummary.scan(RunSummary.java:64)
          at io.hyperfoil.tools.qdup.config.RunSummary.lambda$walk$5(RunSummary.java:58)
          at io.hyperfoil.tools.qdup.cmd.Cmd.walk(Cmd.java:441)
          at io.hyperfoil.tools.qdup.cmd.Cmd.lambda$walk$2(Cmd.java:444)
          at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
          at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1117)
          at io.hyperfoil.tools.qdup.cmd.Cmd.walk(Cmd.java:444)
          at io.hyperfoil.tools.qdup.cmd.Cmd.walk(Cmd.java:433)
          at io.hyperfoil.tools.qdup.config.RunSummary.walk(RunSummary.java:57)
          at io.hyperfoil.tools.qdup.config.RunSummary.scan(RunSummary.java:87)
          at io.hyperfoil.tools.qdup.config.RunSummary.lambda$walk$5(RunSummary.java:58)
          at io.hyperfoil.tools.qdup.cmd.Cmd.walk(Cmd.java:441)
          at io.hyperfoil.tools.qdup.cmd.impl.ScriptCmd.walk(ScriptCmd.java:96)
          at io.hyperfoil.tools.qdup.cmd.Cmd.walk(Cmd.java:433)
          at io.hyperfoil.tools.qdup.config.RunSummary.walk(RunSummary.java:57)
          at io.hyperfoil.tools.qdup.config.RunSummary.lambda$scan$1(RunSummary.java:37)
          at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
          at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1117)
          at io.hyperfoil.tools.qdup.config.RunSummary.lambda$scan$3(RunSummary.java:37)
          at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
          at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1117)
          at io.hyperfoil.tools.qdup.config.RunSummary.lambda$scan$4(RunSummary.java:35)
          at java.base/java.util.HashMap$Values.forEach(HashMap.java:1073)
          at io.hyperfoil.tools.qdup.config.RunSummary.scan(RunSummary.java:34)
          at io.hyperfoil.tools.qdup.config.RunConfigBuilder.buildConfig(RunConfigBuilder.java:635)
          at io.hyperfoil.tools.qdup.QDup.run(QDup.java:525)
          at io.hyperfoil.tools.qdup.QDup.main(QDup.java:444)
  ```

block causing error:
  ```yaml
  create-knative-serving-load:
      - for-each:
          name: index
          input: ${{=[...Array(${{count:1}}).keys()]}}
        then:
        - sh: echo ${{index}}
  ```

**Comment by johnaohara** [comment]
Thanks for sharing, looks like graalvm library on MacOS is calling a native method that no longer exists in JDK22.  

I am not sure of Graal Truffle is supported on JDK22, or even if we expect qDup to work on JDK22. Could you retry with JDK21 or JDK17?

@willr3 what versions of the JDK have we tested qDup with?

**Comment by ShivangGoswami** [comment]
Java Version:
```console
shivanggoswami@Shivangs-MacBook-Pro ~ % java -version
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment (build 21+35-2513)
OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)
```
Scenarios:

- Executes with latest version
  ```console
  shivanggoswami@Shivangs-MacBook-Pro resource-sizing-qdup-scripts % java -jar qDup-7.jar -C -B ./tmp -i ~/.ssh/id_podman_vm sample.yaml       
  17:33:03.466 Running qDup version 0.7.4 @ 89b766f
  17:33:03.467 output path = ./tmp
  17:33:03.467 shell exit code checks enabled
  17:33:03.682 Can not find io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.
  17:33:03.804 json server listening at Shivangs-MacBook-Pro.local:31337
  17:33:04.774 starting 1 scripts
  17:33:04.778 tryme:20@localhost: script-cmd: tryme
  17:33:04.780 tryme:20@localhost: tryme
  17:33:05.225 tryme:20@localhost: whoami
  root
  17:33:05.659 tryme:20@localhost: date
  Tue Oct 31 12:03:05 UTC 2023
  17:33:06.095 tryme:20@localhost: echo Hello, qDup!
  Hello, qDup!
  Finished in 02.211 at ./tmp
  ```
- Executes with version 0.6.21
  ```console
  shivanggoswami@Shivangs-MacBook-Pro resource-sizing-qdup-scripts % java -jar qDup-6.jar -C -B ./tmp -i ~/.ssh/id_podman_vm sample.yaml
  17:37:13.340 [main] INFO  qdup.._tmp - Running qDup version 0.6.18 @ e2f52cc
  17:37:13.809 [main] DEBUG qdup.._tmp.state - run-1698754030063 starting state:
   message = Hello, qDup!
  
  17:37:14.740 [qdup-command-2] INFO  qdup.._tmp - tryme:23@localhost:script-cmd: tryme
  17:37:14.742 [qdup-command-3] INFO  qdup.._tmp - tryme:23@localhost:tryme
  17:37:15.179 [qdup-scheduled-0] INFO  qdup.._tmp - tryme:23@localhost:whoami
  root
  17:37:15.616 [qdup-scheduled-1] INFO  qdup.._tmp - tryme:23@localhost:date
  Tue Oct 31 12:07:15 UTC 2023
  17:37:16.051 [qdup-scheduled-7] INFO  qdup.._tmp - tryme:23@localhost:echo Hello, qDup!
  Hello, qDup!
  17:37:16.066 [qdup-command-9] DEBUG qdup.._tmp.state - run-1698754030063 closing state:
   message = Hello, qDup!
   localhost : 
     tryme : 
       id=7 : 
  
  Finished in 02.264 at ./tmp
  ```
- Executes in version 0.6.13
   ```console
  shivanggoswami@Shivangs-MacBook-Pro resource-sizing-qdup-scripts % java -jar qDup.jar -C -B ./tmp -i ~/.ssh/id_podman_vm sample.yaml 
  17:38:29.211 [main] INFO  io.hyperfoil.tools.qdup.QDup - Starting with output path = ./tmp
  17:38:34.531 [main] INFO  io.hyperfoil.tools.qdup.JsonServer - listening at Shivangs-MacBook-Pro.local:31337
  17:38:34.645 Running qDup version 0.6.13 @ 00a1831
  17:38:34.648 run-1698754109085 starting state:
   message = Hello, qDup!
  
  17:38:34.652 [main] INFO  i.h.tools.qdup.cmd.Dispatcher - starting 0 scripts
  17:38:34.803 [qdup-command-1] INFO  o.a.s.c.u.s.e.EdDSASecurityProviderRegistrar - getOrCreateProvider(EdDSA) created instance of net.i2p.crypto.eddsa.EdDSASecurityProvider
  17:38:34.909 [qdup-command-1] INFO  o.a.s.c.i.DefaultIoServiceFactoryFactory - No detected/configured IoServiceFactoryFactory using Nio2ServiceFactoryFactory
  17:38:34.919 [qdup-command-1] INFO  o.a.s.c.c.h.DefaultConfigFileHostEntryResolver - resolveEffectiveResolver(root@localhost:1234) loaded 9 entries from /Users/shivanggoswami/.ssh/config
  17:38:35.488 [qdup-command-0] INFO  i.h.tools.qdup.cmd.Dispatcher - starting 1 scripts
  17:38:35.488 [qdup-command-0] INFO  i.h.tools.qdup.cmd.Dispatcher - starting nanny
  17:38:35.491 tryme:14@localhost:script-cmd: tryme
  17:38:35.492 tryme:14@localhost:tryme
  17:38:35.830 tryme:14@localhost:whoami
  root
  17:38:36.160 tryme:14@localhost:date
  Tue Oct 31 12:08:35 UTC 2023
  17:38:36.490 tryme:14@localhost:echo Hello, qDup!
  Hello, qDup!
  17:38:36.502 [qdup-command-8] INFO  io.hyperfoil.tools.qdup.Run - run-1698754109085 runPendingDownloads
  17:38:36.502 [qdup-command-8] INFO  io.hyperfoil.tools.qdup.Run - run-1698754109085 -> ./tmp.queueCleanupScripts
  17:38:36.503 [qdup-command-8] INFO  i.h.tools.qdup.cmd.Dispatcher - starting 0 scripts
  17:38:36.504 [qdup-command-9] INFO  io.hyperfoil.tools.qdup.Run - run-1698754109085 runPendingDownloads
  17:38:36.506 run-1698754109085 closing state:
   message = Hello, qDup!
   localhost : 
     tryme : 
       id=7 : 
  
  Finished in 01.879 at ./tmp
  17:38:37.538 [shutdown-abort] WARN  io.hyperfoil.tools.qdup.Run - Skipping cleanup - Abort has been defined to not run any cleanup scripts
  17:38:37.539 [shutdown-abort] WARN  i.h.tools.qdup.cmd.Dispatcher - ignoring stop call when already stopped
   ```

furthermore, for-each block is also working fine with latest version as well.

**Comment by johnaohara** [comment]
> Maybe we should define a support matrix for qDup in the readme file with the versions that were tested as of now, so that new adapters of qDup have a clear picture of qDup prerequisites before trying in different operating systems and architectures cc: @johnaohara @willr3 @stalep

I think this  is a great idea to document what JDK versions qDup is know to work with
