### ISSUE TITLE
Error thrown using multiple dots '.' in dynamic state name 

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/qDup#45]
It used to be possible to dynamically define a state name with multiple dots "." in the name, e.g.;

```
${{APP.name}}.${{VARIANT.name}}.${{CPU.cores}}.pid
```

With yaup now depending on GraalVM js to evaluate state names with parameters, trying to use dynamic state names with multiple dots causes the following exception;

```
11:52:35.005 capture-stats@test:set-state: getting-started.jvm.1.pid 606735
SyntaxError: Unnamed:1:19 Expected ; but found .1
getting-started.jvm.1.pid
                   ^

	at org.graalvm.polyglot.Context.eval(Context.java:370)
	at io.hyperfoil.tools.yaup.StringUtil.populatePattern(StringUtil.java:132)
	at io.hyperfoil.tools.yaup.StringUtil.populatePattern(StringUtil.java:53)
	at io.hyperfoil.tools.qdup.cmd.Cmd.getStateValue(Cmd.java:507)
	at io.hyperfoil.tools.qdup.cmd.Cmd.populateStateVariables(Cmd.java:529)
	at io.hyperfoil.tools.qdup.cmd.Cmd.populateStateVariables(Cmd.java:518)
	at io.hyperfoil.tools.qdup.cmd.Cmd.populateStateVariables(Cmd.java:511)
	at io.hyperfoil.tools.qdup.cmd.impl.Sh.run(Sh.java:41)
	at io.hyperfoil.tools.qdup.cmd.Cmd.doRun(Cmd.java:891)
	at io.hyperfoil.tools.qdup.cmd.ScriptContext.run(ScriptContext.java:431)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

This needs to be fixed in yaup, and the version bumped in qDup

**Comment by johnaohara** [comment]
Example of command being executed;

```
              - sh: docker ps --filter="name=${{APP.name}}-${{VARIANT.name}}" --format="{{.ID}}" | xargs docker inspect | jq '.[].State.Pid'
                then:
                 - set-state: ${{APP.name}}.${{VARIANT.name}}.${{CPU.cores}}.pid
```

**Comment by willr3** [comment]
this should be fixed with the fix in yaup https://github.com/Hyperfoil/yaup/issues/18
