### ISSUE TITLE
NPE running setup scripts

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/qDup#88]
The following NPE is being thrown running setup scripts;

Running with `qDup version 0.6.4-SNAPSHOT @ 5ec2cd0`

````
java.lang.NullPointerException
	at io.hyperfoil.tools.qdup.Env.lambda$getDiff$4(Env.java:211)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.hyperfoil.tools.qdup.Env.getDiff(Env.java:208)
	at io.hyperfoil.tools.qdup.cmd.impl.RoleEnv.getLogOutput(RoleEnv.java:63)
	at io.hyperfoil.tools.qdup.cmd.Cmd.postRun(Cmd.java:997)
	at io.hyperfoil.tools.qdup.cmd.ScriptContext.next(ScriptContext.java:299)
	at io.hyperfoil.tools.qdup.cmd.impl.RoleEnv.run(RoleEnv.java:50)
	at io.hyperfoil.tools.qdup.cmd.Cmd.doRun(Cmd.java:985)
	at io.hyperfoil.tools.qdup.cmd.ScriptContext.run(ScriptContext.java:493)
	at io.hyperfoil.tools.qdup.cmd.ScriptContext.run(ScriptContext.java:399)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
````

**Comment by johnaohara** [comment]
This exception appears to be happening intermittently

**Comment by willr3** [comment]
There appears to be some inconsistency in parsing the environment. I cannot get a reliable recreate but I will be more defensive against `null` while trying to find the cause
